### ISSUE TITLE
Improvement to trimming

### ISSUE THREAD

**Issue by gmemstr** [gmemstr/database-janitor#15]
Either add "keep X rows ordered by" configuration option and/or "remove X duplicate rows with Y column in common".

**Comment by gmemstr** [comment]
build off of work done with configuration in cd90726f8ffe30c523fd2e8779768d7b7af52cfc, introduce keywords rather than rows so:

```yaml
keep_data:
  users:
    col: uid
    rows:
      - 1
      - 3
  user_roles:
    col: uid
    rows: every_other # Or something similar
```

**Comment by gmemstr** [comment]
Actually, much better would be:

```yaml
  user_roles:
    col: uid
    rows: 2
```

Then we can take advantage of the `mod` math function in MySQL. We could also use keywords (every_other etc) but that would require translation and doesn't really have any advantages.
