### ISSUE TITLE
CLI process for generating janitor configuration

### ISSUE THREAD

**Issue by gmemstr** [gmemstr/database-janitor#18]
Since the inclusion of additional YML files within the main config (#17) it's probably worth looking into writing a command line flag and letting it run through the database itself (interactively or otherwise?) to generate a janitor.yml file. I'm not 100% sure the logistics of this since it's not high on my list of priorities but is something to consider.

**Comment by gmemstr** [comment]
build off of work done with configuration in cd90726f8ffe30c523fd2e8779768d7b7af52cfc, introduce keywords rather than rows so:

```yaml
keep_data:
  users:
    col: uid
    rows:
      - 1
      - 3
  user_roles:
    col: uid
    rows: every_other # Or something similar
```
